### ISSUE TITLE
develop shows error

### ISSUE THREAD

**Issue by Remi-C** [Remi-C/interactive_map_tracking#13]
Error when activating hte extension in qgis :+1: 

`Traceback (most recent call last):
  File "C:/PROGRA~1/QGISBR~1/apps/qgis/./python\qgis\utils.py", line 217, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/Remi/.qgis2/python/plugins\interactive_map_tracking\interactive_map_tracking.py", line 290, in initGui
    self.init_plugin()
  File "C:/Users/Remi/.qgis2/python/plugins\interactive_map_tracking\interactive_map_tracking.py", line 377, in init_plugin
    QObject.connect(self.dlg.threshold_extent, SIGNAL("returnPressed ()"), self.thresholdChanged())
TypeError: arguments did not match any overloaded call:
  QObject.connect(QObject, SIGNAL(), QObject, SLOT(), Qt.ConnectionType=Qt.AutoConnection): argument 3 has unexpected type 'NoneType'
  QObject.connect(QObject, SIGNAL(), callable, Qt.ConnectionType=Qt.AutoConnection): argument 3 has unexpected type 'NoneType'
  QObject.connect(QObject, SIGNAL(), SLOT(), Qt.ConnectionType=Qt.AutoConnection): argument 2 has unexpected type 'str'`

**Comment by yoyonel** [comment]
I can't reproduce this bug, try to restart QGIS.
