### ISSUE TITLE
error in develop, when tracking 

### ISSUE THREAD

**Issue by Remi-C** [Remi-C/interactive_map_tracking#14]
Here is the error
Simply zoom in to reproduce

`Traceback (most recent call last):
  File "C:/Documents and Settings/T0111151/.qgis2/python/plugins\interactive_map_tracking\interactive_map_tracking.py", line 589, in canvasExtentsChangedAndRenderComplete
    self.update_track_position()
  File "C:/Documents and Settings/T0111151/.qgis2/python/plugins\interactive_map_tracking\interactive_map_tracking.py", line 938, in update_track_position
    "\tThreshold size= " + str(threshold))
NameError: global name 'threshold' is not defined`

**Comment by Remi-C** [comment]
Solved : 
add "self" before "threshold"

**Comment by Remi-C** [comment]
solved with #8017cba3beb13d935b87d0891325a63bda51e49a

**Comment by yoyonel** [comment]
Yep problem with merge (again :p)
